###
### SfsAdminBundle - Symfony2 project
### (c) Ramine AGOUNE <ramine.agoune@solidlynx.com>
###

services:
#FormFactory
    sfs_admin.form.resolved_type_factory:
        class: Sfs\AdminBundle\Form\Factory\ResolvedFormTypeFactory
    sfs_admin.form.registry:
        class: Sfs\AdminBundle\Form\Factory\FormRegistry
        arguments:
            - ["@form.extension"]
            - "@sfs_admin.form.resolved_type_factory"
    sfs_admin.form.factory:
        class: Symfony\Component\Form\FormFactory
        arguments:
            - "@sfs_admin.form.registry"
            - "@sfs_admin.form.resolved_type_factory"

# Form Types
    sfs_admin.form.type.select:
        class: Sfs\AdminBundle\Form\Type\SelectType
        tags:
            - { name: form.type }
    sfs_admin.form.type.select_entity:
        class: Sfs\AdminBundle\Form\Type\SelectEntityType
        tags:
            - { name: form.type }
    sfs_admin.form.type.tag:
        class: Sfs\AdminBundle\Form\Type\TagType
        tags:
            - { name: form.type }
    sfs_admin.form.type.tag_entity:
        class: Sfs\AdminBundle\Form\Type\TagEntityType
        tags:
            - { name: form.type }
    sfs_admin.form.type.select_list:
        class: Sfs\AdminBundle\Form\Type\SelectListType
        tags:
            - { name: form.type }
    sfs_admin.form.type.select_list_entity:
        class: Sfs\AdminBundle\Form\Type\SelectListEntityType
        tags:
            - { name: form.type }

    sfs_admin.form.type.switch:
        class: Sfs\AdminBundle\Form\Type\SwitchType
        tags:
            - { name: form.type }
    sfs_admin.form.type.slider:
        class: Sfs\AdminBundle\Form\Type\SliderType
        tags:
            - { name: form.type }
    sfs_admin.form.type.color_picker:
        class: Sfs\AdminBundle\Form\Type\ColorPickerType
        tags:
            - { name: form.type }
    sfs_admin.form.type.datetime_picker:
        class: Sfs\AdminBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type }

# Filters
    sfs_admin.filter.doctrine_subscriber:
        class: Sfs\AdminBundle\Listener\FilterSubscriber
        tags:
            - { name: kernel.event_subscriber }

    sfs_admin.form.filter.boolean:
        class: Sfs\AdminBundle\Form\Filter\BooleanFilter
        tags:
            - { name: form.type }
    sfs_admin.form.filter.select_entity:
        class: Sfs\AdminBundle\Form\Filter\SelectEntityFilter
        tags:
            - { name: form.type }
    sfs_admin.form.filter.tag_entity:
        class: Sfs\AdminBundle\Form\Filter\TagEntityFilter
        tags:
            - { name: form.type }
    sfs_admin.form.filter.datetime_picker:
        class: Sfs\AdminBundle\Form\Filter\DateTimePickerFilter
        tags:
            - { name: form.type }
    sfs_admin.form.filter.datetime_range:
        class: Sfs\AdminBundle\Form\Filter\DateTimeRangeFilter
        tags:
            - { name: form.type }
