###
### SfsAdminBundle - Symfony2 project
### (c) Ramine AGOUNE <ramine.agoune@solidlynx.com>
###

sfs_admin_root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: sfs_admin_dashboard
        permanent: true

sfs_admin_dashboard:
    path:  /dashboard
    defaults: { _controller: Sfs\AdminBundle\Controller\PageController::dashboardAction }

# Security routes
sfs_admin_login:
    path:  /login
    defaults: { _controller: Sfs\AdminBundle\Controller\SecurityController::loginAction }

sfs_admin_login_check:
    path: /login-check
    defaults: { _controller: Sfs\AdminBundle\Controller\SecurityController::checkAction }

sfs_admin_logout:
    path:  /logout
    defaults: { _controller: Sfs\AdminBundle\Controller\SecurityController::logoutAction }
