###
### SfsAdminBundle - Symfony4 project
### (c) Ramine AGOUNE <ramine.agoune@solidlynx.com>
###

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    Sfs\AdminBundle\Controller\SecurityController:
        public: true
        tags: ['container.service_subscriber']
        arguments:
            - "@security.authentication_utils"
            - "@security.csrf.token_manager"

    Sfs\AdminBundle\Controller\PageController:
        public: true
        tags: ['container.service_subscriber']

# SFS Admin
    Sfs\AdminBundle\Core\CoreAdmin:
        calls:
            - [setContainer, ["@service_container"]]
        public: false
    sfs.admin.core:
        alias: Sfs\AdminBundle\Core\CoreAdmin
        public: true
#
    Sfs\AdminBundle\Routing\RouteAdminLoader:
        tags:
            - { name: routing.loader }
        arguments:
            - "@sfs.admin.core"
        public: false
    sfs.admin.routing_loader:
        alias: Sfs\AdminBundle\Routing\RouteAdminLoader
        public: true
#
    Sfs\AdminBundle\Menu\MenuBuilder:
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: knp_menu.menu_builder, method: sidebarMenu, alias: sidebar }
            - { name: knp_menu.menu_builder, method: breadcrumbMenu, alias: breadcrumb }
            - { name: knp_menu.menu_builder, method: topbarMenu, alias: topbar }
        public: true
    sfs.admin.menu_builder:
        alias: Sfs\AdminBundle\Menu\MenuBuilder
        public: true

#
## Topbar
    Sfs\AdminBundle\Menu\Topbar\UserBlock:
        arguments:
            - "@twig"
        tags:
            - { name: sfs_admin.menu.topbar }
        public: true
#
## Listeners
    Sfs\AdminBundle\Listener\AdminListener:
        arguments:
            - "@sfs.admin.core"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        public: false
    sfs.admin.action_listener:
        alias: Sfs\AdminBundle\Listener\AdminListener
        public: true
#
## Collectors
    Sfs\AdminBundle\DataCollector\AdminCollector:
        public: false
        arguments:
            - "@sfs.admin.core"
        tags:
            -
                name: data_collector
                template: '@SfsAdmin/DataCollector/admin_collector.html.twig'
                id:       'sfs.admin.admin_collector'
    sfs.admin.admin_collector:
        alias: Sfs\AdminBundle\DataCollector\AdminCollector
        public: true
#
# Twig extensions
    Sfs\AdminBundle\Twig\AdminRouterExtension:
        arguments:
            - "@sfs.admin.core"
        tags:
            - { name: twig.extension }
        public: false
    sfs.admin.twig.url_extension:
        alias: Sfs\AdminBundle\Twig\AdminRouterExtension
        public: true
#
    Sfs\AdminBundle\Twig\OfTypeExtension:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@sfs.admin.core"
        tags:
            - { name: twig.extension }
        public: false
    sfs.admin.twig.of_type:
        alias: Sfs\AdminBundle\Twig\OfTypeExtension
        public: true
#
    Sfs\AdminBundle\Twig\PreferencesExtension:
        arguments:
            - "@service_container"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
        public: false
    sfs.admin.twig.preferences_extension:
        alias: Sfs\AdminBundle\Twig\PreferencesExtension
        public: true
#
    Sfs\AdminBundle\Twig\PropertyAccessExtension:
        tags:
            - { name: twig.extension }
        public: false
    sfs.admin.twig.property_access_extension:
        alias: Sfs\AdminBundle\Twig\PropertyAccessExtension
        public: true
#
    Sfs\AdminBundle\Twig\AdminTemplateExtension:
        arguments:
            - "@sfs.admin.core"
        tags:
            - { name: twig.extension }
        public: false
    sfs.admin.twig.template_extension:
        alias: Sfs\AdminBundle\Twig\AdminTemplateExtension
        public: true
#
