###
### SfsAdminBundle - Symfony2 project
### (c) Ramine AGOUNE <ramine.agoune@solidlynx.com>
###

services:
# SFS Admin
    sfs.admin.core:
        class: Sfs\AdminBundle\Core\CoreAdmin
        calls:
            - [setContainer, ["@service_container"]]
    sfs.admin.routing_loader:
        class: Sfs\AdminBundle\Routing\RouteAdminLoader
        tags:
            - { name: routing.loader }
        arguments:
            - "@sfs.admin.core"
    sfs.admin.menu_builder:
        class: Sfs\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]

## Menus
    sfs.admin.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory: ["@sfs.admin.menu_builder", sidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar }
    sfs.admin.breadcrumb_menu:
        class: Knp\Menu\MenuItem
        factory: ["@sfs.admin.menu_builder", breadcrumbMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumb }
    sfs.admin.topbar_menu:
        class: Knp\Menu\MenuItem
        factory: ["@sfs.admin.menu_builder", topbarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: topbar }
    sfs.admin.subbar_menu:
        class: Knp\Menu\MenuItem
        factory: ["@sfs.admin.menu_builder", subbarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: subbar }

## Topbar
    sfs.admin.topbar_menu.user:
        class: Sfs\AdminBundle\Menu\Topbar\UserBlock
        arguments:
            - "@twig"
        tags:
            - { name: sfs_admin.menu.topbar }

## Listeners
    sfs.admin.action_listener:
        class: Sfs\AdminBundle\Listener\AdminListener
        arguments:
            - "@sfs.admin.core"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#
## Collectors
    sfs.admin.admin_collector:
        class: Sfs\AdminBundle\DataCollector\AdminCollector
        public: false
        arguments:
            - "@sfs.admin.core"
        tags:
            -
                name: data_collector
                template: 'SfsAdminBundle:DataCollector:admin_collector.html.twig'
                id:       'sfs.admin.admin_collector'

# Twig extensions
    sfs.admin.twig.url_extension:
        class: Sfs\AdminBundle\Twig\AdminRouterExtension
        arguments:
            - "@sfs.admin.core"
        tags:
            - { name: twig.extension }
    sfs.admin.twig.of_type:
        class: Sfs\AdminBundle\Twig\OfTypeExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@sfs.admin.core"
        tags:
            - { name: twig.extension }
    sfs.adminu.twig.preferences_extension:
        class: Sfs\AdminBundle\Twig\PreferencesExtension
        arguments:
            - "@service_container"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
    sfs.adminu.twig.property_access_extension:
        class: Sfs\AdminBundle\Twig\PropertyAccessExtension
        tags:
            - { name: twig.extension }
