language: php
php:
    - 5.4
    - 5.5
    - 5.6
services:
    - mysql
before_script:
    - composer install
    - cp Tests/Fixtures/app/config/parameters.yml.travis Tests/Fixtures/app/config/parameters_test.yml
    - php Tests/Fixtures/app/console doctrine:database:create --env=test
    - php Tests/Fixtures/app/console doctrine:schema:create --env=test
script: phpunit -c .

branches:
    # blacklist
    except:
    # whitelist
    only:
        - master
        - develop
        - feature/travis

notifications:
    email:
        -  ramine.agoune@solidlynx.com
